title_html: "<b>n</b>oel <b>arteche</b>"
title: "narteche.github.io"
description: "«If there were a solution to the problems of logic, we should only have to caution ourselves that there was a time when they had not been solved (and then too it must have been possible to live and think)». — Wittgenstein, <cite>Culture and Value</cite>, MS 108 207: 29.6.1930"
url: https://www.narteche.github.io/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/" # the subpath of your site, e.g. "/blog"
cc: by-nc-nd

# Author Information
email: "noel.arteche@cs.lth.se"
contact: "e-mail"
twitter_username: alephnoell
github_username: narteche
#linkedin_username:
google_scholar_username: "https://scholar.google.com/citations?user=-KuPy2gAAAAJ&hl=en"
#curriculum: "cv"
#  url: files/others/cv_sep23.pdf

langs: ["en"]

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - REMDE.md
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
