title_html: "<b>Noel</b> Arteche"
title: "narteche.github.io"
description: "Noel Arteche is a PhD student in theoretical computer science at Lund University."
url: https://www.narteche.github.io/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/" # the subpath of your site, e.g. "/blog"
cc: by-nc-nd

# Author Information
email: "noel.arteche@gmail.com"
contact: "e-mail"
twitter_username: alephnoell
github_username: narteche
#linkedin_username:
#google_scholar_username: 

langs: ["en"]

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - REMDE.md
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
